# Generated by Django 4.2.1 on 2023-07-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_adress1_shippingaddress_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
